#pragma once
#define MESSAGE_SIZE 512
#define SERVER_PORT 7777

// message
#define MESSAGE_END "\r\n\r\n"
#define CMD_PREFIX "cmd:"
#define TXT_PREFIX "txt:"
#define JSON_PREFIX "jsn:"
#define ERROR_PREFIX "err:"
#define MESSAGE_PREFIX_LEN 4

// request
#define REQUEST_ADD_CURRENCY "ADD_CURRENCY"
#define REQUEST_DEL_CURRENCY "DEL_CURRENCY"
#define REQUEST_ADD_CURRENCY_VALUE "ADD_CURRENCY_VALUE"
#define REQUEST_GET_ALL_CURRENCIES "GET_ALL_CURRENCIES"
#define REQUEST_GET_CURRENCY_HISTORY "GET_CURRENCY_HISTORY"

#define CHUNK_REQUEST_MESSAGE 64
#define CHUNK_SUCCESS_MESSAGE 32
#define CONTENT_MESSAGE 16

#define UDP_PACKET_SIZE 256
